"""
Data models for deal summarization.
"""
from datetime import datetime
from typing import List, Optional, Dict, Any, Union
from pydantic import BaseModel, Field, field_validator


class Stakeholder(BaseModel):
    """A stakeholder involved in the deal."""
    name: Optional[str] = None
    role: Optional[str] = None
    email: Optional[str] = None
    contact: Optional[str] = None  # Alternative to email
    company: Optional[str] = None
    engagement_level: Optional[str] = None  # "high", "medium", "low"

    @field_validator('name', mode='before')
    @classmethod
    def ensure_name_or_contact(cls, v, info):
        """If name is missing, try to use email or contact as name."""
        if not v and info.data:
            # Try to extract name from email or contact
            email = info.data.get('email') or info.data.get('contact')
            if email:
                # Use email prefix as name
                return email.split('@')[0].replace('.', ' ').title()
        return v or "Unknown"


class KeyInsight(BaseModel):
    """A key insight extracted from the deal context."""
    category: str  # "opportunity", "risk", "concern", "requirement"
    description: str
    source: Optional[str] = None  # Where this insight came from (e.g., "Note from 2025-11-07")
    importance: Optional[str] = None  # "high", "medium", "low"


class InteractionSummary(BaseModel):
    """Summary of a key interaction."""
    date: str
    type: Optional[str] = "note"  # "note", "task", "call"
    summary: Optional[str] = None
    participants: List[str] = Field(default_factory=list)

    @field_validator('type', mode='before')
    @classmethod
    def ensure_type(cls, v):
        """Provide default type if missing."""
        return v or "note"

    @field_validator('summary', mode='before')
    @classmethod
    def ensure_summary(cls, v, info):
        """Provide default summary if missing, try to extract from other fields."""
        if not v and info.data:
            # Try common alternative field names
            for field in ['description', 'detail', 'details', 'note', 'content']:
                if field in info.data:
                    return info.data[field]
        return v or "No summary provided"


class DealSummary(BaseModel):
    """
    Complete deal summary generated by AI.
    """
    # Basic Info
    deal_name: str
    deal_id: str
    company_name: Optional[str] = None
    deal_stage: Optional[str] = None
    deal_value: Optional[str] = None

    # Executive Summary
    executive_summary: str = Field(
        description="2-3 sentence high-level summary of the deal status"
    )

    # Stakeholders
    stakeholders: List[Stakeholder] = Field(
        default_factory=list,
        description="Key people involved in the deal"
    )

    # Deal Context
    deal_context: str = Field(
        description="Detailed context about the deal, customer needs, and situation"
    )

    # Key Insights
    opportunities: List[KeyInsight] = Field(
        default_factory=list,
        description="Opportunities identified"
    )
    risks: List[KeyInsight] = Field(
        default_factory=list,
        description="Risks and concerns identified"
    )
    requirements: List[KeyInsight] = Field(
        default_factory=list,
        description="Customer requirements and needs"
    )

    # Interaction Timeline
    recent_interactions: List[InteractionSummary] = Field(
        default_factory=list,
        description="Summary of recent key interactions"
    )

    # Current Status
    current_status: str = Field(
        description="Current state of the deal and recent developments"
    )

    # Next Steps Context
    next_steps_context: str = Field(
        description="Context for determining next best actions"
    )

    # Metadata
    generated_at: str = Field(
        default_factory=lambda: datetime.now().isoformat()
    )
    data_sources: Union[List[str], str] = Field(
        default_factory=list,
        description="What data was used for this summary"
    )

    @field_validator('data_sources', mode='before')
    @classmethod
    def validate_data_sources(cls, v):
        """Convert string to list if needed."""
        if isinstance(v, str):
            return [v]
        return v or []

    @field_validator('recent_interactions', mode='before')
    @classmethod
    def validate_recent_interactions(cls, v):
        """Convert dict/string to empty list if needed."""
        if isinstance(v, dict):
            # Claude sometimes returns {"summary": "text"} instead of a list
            return []
        if isinstance(v, str):
            # Claude sometimes returns a text description instead of a list
            return []
        return v or []

    @field_validator('requirements', mode='before')
    @classmethod
    def validate_requirements(cls, v):
        """Fix requirements that have 'requirement' field instead of 'category' and 'description'."""
        if not isinstance(v, list):
            return v or []

        fixed_items = []
        for item in v:
            if isinstance(item, dict) and 'requirement' in item:
                # Convert from {'requirement': 'text', 'source': 'x'}
                # to {'category': 'requirement', 'description': 'text', 'source': 'x'}
                fixed_items.append({
                    'category': 'requirement',
                    'description': item.get('requirement', ''),
                    'source': item.get('source'),
                    'importance': item.get('importance')
                })
            else:
                fixed_items.append(item)
        return fixed_items

    confidence_score: Optional[float] = Field(
        default=None,
        description="AI confidence in the summary (0-1)"
    )

    # Change Tracking
    changes_since_last_summary: Optional[str] = Field(
        default=None,
        description="AI-generated overview of what changed since the last summary"
    )
    data_version: Optional[str] = Field(
        default=None,
        description="Hash of the enriched data used for this summary"
    )
    is_cached: bool = Field(
        default=False,
        description="Whether this summary was retrieved from cache"
    )
    previous_summary_date: Optional[str] = Field(
        default=None,
        description="Timestamp of the previous summary (if this is an update)"
    )


class SummarizationRequest(BaseModel):
    """Request for deal summarization."""
    enriched_data: Dict[str, Any]
    focus_areas: Optional[List[str]] = None
    max_length: Optional[int] = None
